[phases.setup]
cmds = ["curl -fsSL https://deb.nodesource.com/setup_18.x | bash -", "apt-get install -y nodejs", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[providers.node]
version = "18"
